# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"APP_ID": "00_core.ipynb",
         "APP_SECRET": "00_core.ipynb",
         "TOKEN": "00_core.ipynb",
         "USER_ID": "00_core.ipynb",
         "SHEET": "00_core.ipynb",
         "SH": "00_core.ipynb",
         "get_df": "00_core.ipynb",
         "get_worksheet": "00_core.ipynb",
         "write_df": "00_core.ipynb",
         "get_followers": "01_followers.ipynb",
         "get_new_followers": "01_followers.ipynb",
         "get_updated_followers": "01_followers.ipynb",
         "save_followers": "01_followers.ipynb",
         "make_change": "01_followers.ipynb",
         "save_change": "01_followers.ipynb",
         "update": "01_followers.ipynb",
         "AD_ACC_ID": "02_ads.ipynb",
         "account": "02_ads.ipynb",
         "get_dif": "02_ads.ipynb",
         "COLUMNS": "02_ads.ipynb",
         "get_insights": "02_ads.ipynb",
         "get_action": "02_ads.ipynb",
         "get_followers_change": "02_ads.ipynb",
         "add_country_total": "02_ads.ipynb",
         "add_followers": "02_ads.ipynb",
         "get_countries": "02_ads.ipynb",
         "add_total": "02_ads.ipynb",
         "get_insights_df": "02_ads.ipynb",
         "more_stats": "02_ads.ipynb",
         "create_insights": "02_ads.ipynb"}

modules = ["core.py",
           "followers.py",
           "ads.py"]

doc_url = "https://manycoding.github.io/tomorrowswig_followers/"

git_url = "https://github.com/manycoding/tomorrowswig_followers/tree/master/"

def custom_doc_links(name): return None
