# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"APP_ID": "01_ads.ipynb",
         "APP_SECRET": "01_ads.ipynb",
         "TOKEN": "01_ads.ipynb",
         "USER_ID": "01_ads.ipynb",
         "SHEET": "01_ads.ipynb",
         "SH": "01_ads.ipynb",
         "get_followers": "00_followers.ipynb",
         "get_df": "00_followers.ipynb",
         "get_worksheet": "00_followers.ipynb",
         "write_df": "00_followers.ipynb",
         "get_updated_followers": "00_followers.ipynb",
         "save_followers": "00_followers.ipynb",
         "save_change": "00_followers.ipynb",
         "make_change": "00_followers.ipynb",
         "lambda_handler": "00_followers.ipynb",
         "AD_ACC_ID": "01_ads.ipynb"}

modules = ["followers/api.py",
           "ads/api.py"]

doc_url = "https://manycoding.github.io/tomorrowswig_followers/"

git_url = "https://github.com/manycoding/tomorrowswig_followers/tree/master/"

def custom_doc_links(name): return None
