# AUTOGENERATED! DO NOT EDIT! File to edit: 01_ads.ipynb (unless otherwise specified).

__all__ = ['APP_ID', 'APP_SECRET', 'TOKEN', 'USER_ID', 'SHEET', 'AD_ACC_ID', 'SH']

# Cell
from datetime import datetime
import os
from typing import *

import click
import gspread
from gspread.models import *
import pandas as pd
from pyfacebook import IgProApi
from pyfacebook.error import *

APP_ID = os.environ.get("APP_ID")
APP_SECRET = os.environ.get("APP_SECRET")
TOKEN = os.environ.get("TOKEN")
USER_ID = os.environ.get("USER_ID")
SHEET = os.environ.get("SHEET", "Followers API")
AD_ACC_ID = os.environ.get("AD_ACC_ID")
SH = gspread.service_account(filename=path.parent/"creds.json").open(SHEET)
# SH = gspread.service_account(filename=path.parent/"careful-form-283418-d1afb9670368.json").open("Test of Followers API)
